- name: Check value of cups_disable_browsed
  assert:
    that:
      - cups_disable_browsed in [True, False, None]

- name: Install CUPS printing service
  package:
    name: "cups"
    state: present

- name: Enable cups service
  service:
    name: cups
    enabled: yes

- name: Start cups service
  service:
    name: cups
    state: started


# We modify cups-browsed.conf, so let's make sure it is installed.
- block:
    - name: Install cups-browsed [deb package name]
      package:
        name: cups-browsed
        state: present
  rescue:
    - name: Install cups-browsed [old redhat package name]
      package:
        name: cups-filters
        state: present
  when: cups_disable_browsed != True

- name: Get list of services
  service_facts:

- name: Check if cups-browsed service exists
  set_fact:
    cups_browsed_service_exists:
      "{{ 'cups-browsed.service' in services or
          'cups-browsed' in services }}"

- name: Enable cups-browsed service (if desired)
  service:
    name: cups-browsed
    enabled: True
  when: cups_disable_browsed == False

- name: Start cups-browsed service (if desired)
  service:
    name: cups-browsed
    state: started
  when: cups_disable_browsed == False

- name: Disable cups-browsed service (if desired)
  service:
    name: cups-browsed
    enabled: False
  when: cups_disable_browsed == True and
            cups_browsed_service_exists

- name: Stop cups-browsed service (if desired)
  service:
    name: cups-browsed
    state: stopped
  when: cups_disable_browsed == True and
            cups_browsed_service_exists

- name: Set cups-browsed RemoteProtocols
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    backup: yes
    regexp: '^( *# *)?BrowseRemoteProtocols '
    line: 'BrowseRemoteProtocols {{ cups_browsed_remote_protocols }}'
  notify: [ 'Restart cups-browsed' ]
  when: cups_disable_browsed != True

- name: Set cups ErrorPolicy
  lineinfile:
    path: /etc/cups/cupsd.conf
    backup: yes
    regexp: '^( *# *)?ErrorPolicy '
    line: 'ErrorPolicy {{ cups_error_policy }}'
  notify: [ 'Apply ErrorPolicy', 'Restart cups' ]
